//@version=5
indicator('Condition', overlay=true)

// Input options
// averageData = input.source(close, title="Average Data Source")

fastLength = 9
slowLength = 20
breakOutDist = 3
var float crossOverLongHigh = -1
var float stopLoss = -1
var bool buy = false
plotShapeBuy = false
plotShapeSell = false
plotConsideration = false

// Calculate exponential moving averages
//fastAverage = ta.ema(close, fastLength)
fastAverage = request.security("TSLA", "5", ta.ema(close,fastLength))
slowAverage = request.security("TSLA", "5", ta.ema(close,slowLength))
barsRight = input(5)

// Plot averages
plot(fastAverage, color=color.blue, title="Fast EMA")
plot(slowAverage, color=color.fuchsia, title="Slow EMA")

if fastAverage > slowAverage
    if close < fastAverage and close > slowAverage and not plotConsideration
        crossOverLongHigh := high
        stopLoss := slowAverage
        plotConsideration := true
    else
        if close > crossOverLongHigh + breakOutDist and not buy
            plotShapeBuy := true
            buy := true
        else if (close < stopLoss or close > 2.002 * crossOverLongHigh - stopLoss) and buy
            plotShapeSell := true
            buy := false
            plotConsideration := false
plot(crossOverLongHigh, color=color.green, title="Cross Over")
plot(stopLoss, color = color.red, title="Stop Loss")
plot(2.002 * crossOverLongHigh - stopLoss, color = color.orange, title="Profit Target")
// plotshape(plotConsideration,text="CONSIDERING", style=shape.triangledown, location=location.belowbar, color=color.orange, size=size.small)
plotshape(plotShapeBuy,text="BUY LONG", style=shape.triangleup, location=location.belowbar, color=color.green, size=size.small)
plotshape(plotShapeSell,text="SELL LONG", style=shape.triangledown, location=location.belowbar, color=color.red, size=size.small)
    